<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>dermakardex_backend</RootNamespace>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
        <PackageReference Include="EntityFrameworkCore.CreatedUpdatedDate" Version="8.0.0"/>
        <PackageReference Include="Humanizer" Version="2.14.1"/>        
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.6"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10"/>        
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3"/>        
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10"/>
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0"/>        
        <PackageReference Include="Cortex.Mediator" Version="2.1.0"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="Shared\.DS_Store" />
      <Content Include="Shared\Application\.DS_Store" />
      <Content Include="Shared\Application\Internal\.DS_Store" />
      <Content Include="Shared\Infrastructure\.DS_Store" />
      <Content Include="Shared\Infrastructure\Documentation\.DS_Store" />
      <Content Include="Shared\Infrastructure\Documentation\OpenApi\.DS_Store" />
      <Content Include="Shared\Infrastructure\Documentation\OpenApi\Configuration\.DS_Store" />
      <Content Include="Shared\Infrastructure\Interfaces\.DS_Store" />
      <Content Include="Shared\Infrastructure\Interfaces\ASP\.DS_Store" />
      <Content Include="Shared\Infrastructure\Interfaces\ASP\Configuration\.DS_Store" />
      <Content Include="Shared\Infrastructure\Mediator\.DS_Store" />
      <Content Include="Shared\Infrastructure\Mediator\Cortex\.DS_Store" />
      <Content Include="Shared\Infrastructure\Mediator\Cortex\Configuration\.DS_Store" />
      <Content Include="Shared\Infrastructure\Mediator\Cortex\Configuration\Extensions\.DS_Store" />
      <Content Include="Shared\Infrastructure\Persistence\.DS_Store" />
      <Content Include="Shared\Infrastructure\Persistence\EFC\.DS_Store" />
      <Content Include="Shared\Infrastructure\Persistence\EFC\Configuration\.DS_Store" />
    </ItemGroup>

</Project>
