// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dermakardex_backend.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace dermakardex_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Products.Domain.Model.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("integer")
                        .HasColumnName("laboratory_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Presentation")
                        .HasColumnType("integer")
                        .HasColumnName("presentation");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<int>("StockAlertThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("stock_alert_threshold");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("p_k_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Products.Domain.Model.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_brands");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Products.Domain.Model.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Products.Domain.Model.Entities.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_laboratories");

                    b.ToTable("laboratories", (string)null);
                });

            modelBuilder.Entity("Products.Domain.Model.Entities.StockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_full_name");

                    b.HasKey("Id")
                        .HasName("p_k_product_stock_entries");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("i_x_product_stock_entries_product_id");

                    b.ToTable("product_stock_entries", (string)null);
                });

            modelBuilder.Entity("Products.Domain.Model.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerDni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("customer_dni");

                    b.Property<string>("CustomerFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_full_name");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<string>("Observation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observation");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date")
                        .HasColumnName("sale_date");

                    b.Property<TimeOnly>("SaleTime")
                        .HasColumnType("time")
                        .HasColumnName("sale_time");

                    b.Property<string>("SellerFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("seller_full_name");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticket_number");

                    b.HasKey("Id")
                        .HasName("p_k_sales");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.Model.Entities.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_value");

                    b.Property<int>("Presentation")
                        .HasColumnType("integer")
                        .HasColumnName("presentation");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.HasKey("Id")
                        .HasName("p_k_sale_items");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("i_x_sale_items_sale_id");

                    b.ToTable("sale_items", (string)null);
                });

            modelBuilder.Entity("Sales.Domain.Model.Entities.SalePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<int?>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.HasKey("Id")
                        .HasName("p_k_sale_payments");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("i_x_sale_payments_sale_id");

                    b.ToTable("sale_payments", (string)null);
                });

            modelBuilder.Entity("Products.Domain.Model.Aggregates.Product", b =>
                {
                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "MaxDiscountAmount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("max_discount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("max_discount_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_products");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_products_products_id");
                        });

                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "PurchasePrice", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("purchase_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("purchase_price_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_products");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_products_products_id");
                        });

                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "SalePrice", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("sale_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("sale_price_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_products");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_products_products_id");
                        });

                    b.OwnsOne("Products.Domain.Model.ValueObjects.Discount", "Discount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("discount_type");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("discount_value");

                            b1.HasKey("Id")
                                .HasName("p_k_products");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_products_products_id");
                        });

                    b.Navigation("Discount")
                        .IsRequired();

                    b.Navigation("MaxDiscountAmount")
                        .IsRequired();

                    b.Navigation("PurchasePrice")
                        .IsRequired();

                    b.Navigation("SalePrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Products.Domain.Model.Entities.StockEntry", b =>
                {
                    b.HasOne("Products.Domain.Model.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_product_stock_entries_products_product_id");

                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "TotalInvestment", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_investment_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_investment_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_product_stock_entries");

                            b1.ToTable("product_stock_entries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_product_stock_entries_product_stock_entries_id");
                        });

                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "UnitPurchasePrice", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("unit_purchase_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_purchase_price_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_product_stock_entries");

                            b1.ToTable("product_stock_entries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_product_stock_entries_product_stock_entries_id");
                        });

                    b.Navigation("TotalInvestment")
                        .IsRequired();

                    b.Navigation("UnitPurchasePrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "Total", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_sales");

                            b1.ToTable("sales");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_sales_sales_id");
                        });

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Domain.Model.Entities.SaleItem", b =>
                {
                    b.HasOne("Sales.Domain.Model.Aggregates.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_sale_items_sales_sale_id");

                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "BaseUnitPrice", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("base_unit_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("base_unit_price_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_sale_items");

                            b1.ToTable("sale_items");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_sale_items_sale_items_id");
                        });

                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "LineTotal", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("line_total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("line_total_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_sale_items");

                            b1.ToTable("sale_items");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_sale_items_sale_items_id");
                        });

                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_price_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_sale_items");

                            b1.ToTable("sale_items");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_sale_items_sale_items_id");
                        });

                    b.Navigation("BaseUnitPrice")
                        .IsRequired();

                    b.Navigation("LineTotal")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Domain.Model.Entities.SalePayment", b =>
                {
                    b.HasOne("Sales.Domain.Model.Aggregates.Sale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_sale_payments_sales_sale_id");

                    b.OwnsOne("Shared.Domain.Model.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("payment_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("payment_currency");

                            b1.HasKey("Id")
                                .HasName("p_k_sale_payments");

                            b1.ToTable("sale_payments");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_sale_payments_sale_payments_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
